name: Build & Test reusable
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
jobs:
  build-y-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurando JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
      - name: Cacheando paquetes Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build & Test
        run: ./mvnw clean verify
        env:
          SPRING_PROFILES_ACTIVE: dev
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}