name: Principal que usa plantilla
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  pruebita:
    uses: ./.github/workflows/ejemplo5.yml
    with:
      java-version: '26'
  deploy-staging:
    needs: pruebita
    if: github.ref == 'refs/heads/develop'
    runs-on: windows-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Configurando JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Compilando el *.jar
        run: ./mvnw clean package -DskipTests
        env:
          SPRING_PROFILES_ACTIVE: dev
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: Deploy a staging
        run: |
          echo "Deploy a STAGING..."
          # curl -X POST https://staging.miapi.com/deploy -H "Authorization: Bearer ${{ secrets.STAGING_TOKEN }}"
  deploy-prod:
    needs: pruebita
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    environment:
      name: production
      url: https://miapi.com
    steps:
      - uses: actions/checkout@v4
      - name: Configurando JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Compilando el *.jar
        run: ./mvnw clean package -DskipTests
        env:
          SPRING_PROFILES_ACTIVE: dev
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: Deploy a producción
        run: |
          echo "Deploy a PRODUCCIÓN..."
          # curl -X POST https://prod.miapi.com/deploy -H "Authorization: Bearer ${{ secrets.PROD_TOKEN }}"